# Generated by Django 4.0.1 on 2022-01-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='content',
            field=models.TextField(),
        ),
    ]
