# Generated by Django 4.1.1 on 2022-09-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('ENTERTAINMENT', 'Entertainment'), ('TECHNOLOGY', 'Technology'), ('GAMES', 'Games'), ('MARKETING/SALES', 'Marketing/Sales'), ('OTHERS', 'Others')], max_length=30),
        ),
    ]
