# Generated by Django 4.0.1 on 2022-01-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postblog',
            name='author',
        ),
    ]
