# Generated by Django 4.0.1 on 2022-02-15 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
