# Generated by Django 4.0.1 on 2022-01-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_postblog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='category',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
