# Generated by Django 4.0.1 on 2022-01-27 17:31

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_postblog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='slug',
            field=autoslug.fields.AutoSlugField(default = 1, editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
