# Generated by Django 3.2.7 on 2022-01-28 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0002_remove_postblog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='written by '),
            preserve_default=False,
        ),
    ]
