# Generated by Django 3.2.7 on 2022-01-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_postblog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
