# Generated by Django 4.0.1 on 2022-02-16 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_draft_blog_publish_blog_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='update_time',
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default=datetime.datetime(2022, 2, 16, 11, 52, 9, 672231, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
