# Generated by Django 3.2.5 on 2022-07-13 10:42

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0003_blog_draft_blog_publish_blog_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='update_time',
        ),
        migrations.AddField(
            model_name='blog',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=False, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
