# Generated by Django 4.0.1 on 2022-01-27 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0004_remove_postblog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='author',
            field=models.ForeignKey(default = 1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='written by '),
            preserve_default=False,
        ),
    ]
