# Generated by Django 3.2.7 on 2022-02-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_postblog_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postblog',
            name='blog_image',
        ),
    ]
