# Generated by Django 4.0.1 on 2022-02-17 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0004_remove_blog_draft_remove_blog_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=False, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
