# Generated by Django 4.0.1 on 2022-02-03 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_postblog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('ANDROID', 'Android'), ('PC', 'PC'), ('Machine Learning', 'Machine Learning'), ('OFFERS', 'Offers'), ('GAMING', 'Gaming'), ('OTHERS', 'Others')], default='OTHERS', max_length=30),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
