# Generated by Django 4.0.1 on 2022-02-03 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_postblog_category_alter_postblog_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
