# Generated by Django 4.0.1 on 2022-02-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_postblog_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('ANDROID', 'Android'), ('PC', 'PC'), ('Machine Learning', 'Machine Learning'), ('OFFERS', 'Offers'), ('GAMING', 'Gaming'), ('OTHERS', 'Others')], max_length=30),
        ),
    ]
