# Generated by Django 4.0.1 on 2022-02-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_postblog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
